alien dance lmao

diff --git a/voscfg/files/usr/lib/voscfg/adduser b/voscfg/files/usr/lib/voscfg/adduser
--- a/voscfg/files/usr/lib/voscfg/adduser
+++ b/voscfg/files/usr/lib/voscfg/adduser
@@ -1,6 +1,8 @@
 #!/bin/sh
 DISTRO_NAME="$(cat /usr/lib/os-release | grep -i "PRETTY_NAME" | cut -d '=' -f 2 | sed 's/"//g')"
 SCRIPT_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
+SCRIPT_USER=$(whoami)
+BACKTITLE="$DISTRO_NAME settings [$SCRIPT_USER]"
 Help() {
 	echo "Usage: $(basename $0) [OPTIONS] <username>"
 	echo "Options:"
@@ -51,28 +53,28 @@ done
 
 if [ -z "$USERNAME" ]; then ## Prompt for a username
 	DIALOG=1
-	USERNAME="$(dialog --stdout --backtitle "$DISTRO_NAME settings" --title "Add user" --inputbox "Enter username of new user. It must not:\n - Be longer than 32 characters\n - Include capital letters, dots or colons\n - End with a hyphen (-)\n - Be reserved for use by the system (e.g. root, ftp, nobody, mail, guest, shared)" 0 0)"
+	USERNAME="$(dialog --stdout --backtitle "$BACKTITLE" --title "Add user" --inputbox "Enter username of new user. It must not:\n - Be longer than 32 characters\n - Include capital letters, dots or colons\n - End with a hyphen (-)\n - Be reserved for use by the system (e.g. root, ftp, nobody, mail, guest, shared)" 0 0)"
 	[ -z "$USERNAME" ] && exit 125
 	## Check if user exists (including system users)
 	unset USERS; for EXISTING_USER in $(cut -d: -f1 /etc/passwd); do USERS="$USERS $EXISTING_USER"; done
 	if [[ "$USERS" == *"$USERNAME"* ]]; then
-		if [ "$DIALOG" == 1 ]; then dialog --backtitle "$DISTRO_NAME settings" --title "Error" --msgbox "User \"$USERNAME\" already exists!" 0 0
+		if [ "$DIALOG" == 1 ]; then dialog --backtitle "$BACKTITLE" --title "Error" --msgbox "User \"$USERNAME\" already exists!" 0 0
 		else echo "[ERROR] User \"$USERNAME\" already exists!"; fi
 		exit 1
 	elif [ "$USERNAME" == "guest" ]; then
-		if [ "$DIALOG" == 1 ]; then dialog --backtitle "$DISTRO_NAME settings" --title "Error" --msgbox "You cannot create a guest account here! To enable the guest user, go back and select \"Enable guest account\"." 0 0
+		if [ "$DIALOG" == 1 ]; then dialog --backtitle "$BACKTITLE" --title "Error" --msgbox "You cannot create a guest account here! To enable the guest user, go back and select \"Enable guest account\"." 0 0
 		else echo "You cannot create a guest account here! To enable the guest user, go back and select \"Enable guest account\"."; fi
 		exit 1
 	fi
 	if [ "$ADMIN" == 0 ]; then # Ask to make admin
-		dialog --backtitle "$DISTRO_NAME settings" --title "Add user" --yesno "Make $USERNAME an administrator (add to wheel and sys groups)?" 0 0 && ADMIN=1
+		dialog --backtitle "$BACKTITLE" --title "Add user" --yesno "Make $USERNAME an administrator (add to wheel and sys groups)?" 0 0 && ADMIN=1
 	fi
-	ADD_TO_GROUPS="$ADD_TO_GROUPS,$(dialog --stdout --backtitle "$DISTRO_NAME settings" --title "Add user" --inputbox "Enter a comma separated list of additional groups to add $USERNAME to (optional)." 0 0)"
+	ADD_TO_GROUPS="$ADD_TO_GROUPS,$(dialog --stdout --backtitle "$BACKTITLE" --title "Add user" --inputbox "Enter a comma separated list of additional groups to add $USERNAME to (optional)." 0 0)"
 	if [ "$ENCRYPT" == 0 ]; then # Ask to encrypt home directory
-		dialog --backtitle "$DISTRO_NAME settings" --title "Add user" --yesno "Would you like to encrypt $USERNAME's home directory with FScrypt?\nPlease note that only file data is encrypted, not file metadata." 0 0 && ENCRYPT=1 && NOPASSWD=0
+		dialog --backtitle "$BACKTITLE" --title "Add user" --yesno "Would you like to encrypt $USERNAME's home directory with FScrypt?\nPlease note that only file data is encrypted, not file metadata." 0 0 && ENCRYPT=1 && NOPASSWD=0
 	fi
 	if [ "$NOPASSWD" == 0 ] && [ "$ENCRYPT" == 0 ]; then
-		dialog --backtitle "$DISTRO_NAME settings" --title "Add user" --yesno "Would you like to set a password for $USERNAME?" 0 0 || NOPASSWD=1
+		dialog --backtitle "$BACKTITLE" --title "Add user" --yesno "Would you like to set a password for $USERNAME?" 0 0 || NOPASSWD=1
 	fi
 fi
 
@@ -82,7 +84,7 @@ passwd -d "$USERNAME"
 if [ "$NOPASSWD" == 0 ]; then
 	clear; CONTINUE=0; while [ "$CONTINUE" == 0 ]; do
 		if [ "$DIALOG" == 1 ]; then
-			PASSWORD1="$(dialog --stdout --backtitle "$DISTRO_NAME settings" --title "Add user" --passwordbox "Enter a secure password for \"$USERNAME\". It must:\n - Be at least 8 characters long\n - Have at least 1 digit, 1 uppercase letter and 1 lowercase letter\n - Not contain commonly used words or passwords (including swear words), even with character substitution, as modern dictionary attacks can easily work around those\n - Contain personal information, like date/place of birth, mother's maiden name, pet names, favourite band/video game etc\n - Be too easy to guess by others\nSee also https://wiki.archlinux.org/title/Security#Passwords\nYou will not see anything you type. This is for security reasons. When you have entered your password, press enter." 0 0)"
+			PASSWORD1="$(dialog --stdout --backtitle "$BACKTITLE" --title "Add user" --passwordbox "Enter a secure password for \"$USERNAME\". It must:\n - Be at least 8 characters long\n - Have at least 1 digit, 1 uppercase letter and 1 lowercase letter\n - Not contain commonly used words or passwords (including swear words), even with character substitution, as modern dictionary attacks can easily work around those\n - Contain personal information, like date/place of birth, mother's maiden name, pet names, favourite band/video game etc\n - Be too easy to guess by others\nSee also https://wiki.archlinux.org/title/Security#Passwords\nYou will not see anything you type. This is for security reasons. When you have entered your password, press enter." 0 0)"
 		else
 			echo "Enter a secure password for \"$USERNAME\". It must:"
 			echo " - Be at least 8 characters long\n - Have at least 1 digit, 1 uppercase letter and 1 lowercase letter"
@@ -95,7 +97,7 @@ if [ "$NOPASSWD" == 0 ]; then
 		if [ -z "$PASSWORD1" ]; then
 			if [ "$ENCRYPT" == 1 ]; then
 				if [ "$DIALOG" == 1 ]; then
-					dialog --backtitle "$DISTRO_NAME settings" --title "Warning" --yesno "Encryption was requested but no password was provided.\nTo enable encryption, you must set a password.\nSet a password for $USERNAME?" 0 0 || (NOPASSWD=1; CONTINUE=1)
+					dialog --backtitle "$BACKTITLE" --title "Warning" --yesno "Encryption was requested but no password was provided.\nTo enable encryption, you must set a password.\nSet a password for $USERNAME?" 0 0 || (NOPASSWD=1; CONTINUE=1)
 				else
 					echo "Encryption was requested but no password was provided."
 					echo "To enable encryption, you must set a password."
@@ -106,11 +108,11 @@ if [ "$NOPASSWD" == 0 ]; then
 			else NOPASSWD=1; CONTINUE=1; fi
 		else
 			if [ "$DIALOG" == 1 ]; then
-				PASSWORD2="$(dialog --stdout --backtitle "$DISTRO_NAME settings" --title "Add user" --passwordbox "Enter the same password again." 0 0)"
+				PASSWORD2="$(dialog --stdout --backtitle "$BACKTITLE" --title "Add user" --passwordbox "Enter the same password again." 0 0)"
 			else stty -echo; printf "Confirm password for \"$USERNAME\""; unset PASSWORD2; read PASSWORD2; printf "\n"; stty echo; fi
 			if [ "$PASSWORD1" == "$PASSWORD2" ]; then (echo "$PASSWORD1"; echo "$PASSWORD1") | passwd "$USERNAME"; CONTINUE=1
 			else
-				if [ "$DIALOG" == 1 ]; then dialog --backtitle "$DISTRO_NAME settings" --title "Error" --msgbox "Passwords do not match." 0 0
+				if [ "$DIALOG" == 1 ]; then dialog --backtitle "$BACKTITLE" --title "Error" --msgbox "Passwords do not match." 0 0
 				else clear; echo "[ERROR] Passwords do not match."; fi
 			fi
 		fi
@@ -130,7 +132,7 @@ chown "$USERNAME":"$USERNAME" "/home/$USERNAME" "/home/.tmp/$USERNAME"
 chmod 750 "/home/$USERNAME" "/home/.tmp/$USERNAME"
 if [ "$NOPASSWD" == 1 ] && [ "$ENCRYPT" == 1 ]; then
 	ENCRYPT=0
-	if [ "$DIALOG" == 1 ]; then dialog --backtitle "$DISTRO_NAME settings" --title "Warning" --msgbox "Encryption was requested but no password was set. Not encrypting home directory." 0 0
+	if [ "$DIALOG" == 1 ]; then dialog --backtitle "$BACKTITLE" --title "Warning" --msgbox "Encryption was requested but no password was set. Not encrypting home directory." 0 0
 	else echo "[WARNING] Encryption was requested but no password was set. Not encrypting home directory."; fi
 fi
 if [ "$ENCRYPT" == 1 ] && [ "$NOPASSWD" == 0 ]; then
