installer

diff --git a/vapour-os/files/opt/vapour-os/hostname b/vapour-os/files/opt/vapour-os/hostname
--- a/vapour-os/files/opt/vapour-os/hostname
+++ b/vapour-os/files/opt/vapour-os/hostname
@@ -2,7 +2,7 @@
 [ $(whoami) != "root" ] && echo "[ERROR] You must run this script with root priviliges." && exit 1
 SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
 HOST_NAME=$1
-[ -z $HOST_NAME ] && echo "[ERROR] You must specify a hostname!" && exit 1
+[ -z $HOST_NAME ] && echo "[ERROR] No hostname specified - will default to vapour-os." && exit 1
 echo $HOST_NAME > /etc/hostname
 echo "127.0.0.1 localhost" > /etc/hosts
 echo "::1 localhost" >> /etc/hosts
diff --git a/vapour-os/files/opt/vapour-os/keymap b/vapour-os/files/opt/vapour-os/keymap
--- a/vapour-os/files/opt/vapour-os/keymap
+++ b/vapour-os/files/opt/vapour-os/keymap
@@ -2,7 +2,7 @@
 [ $(whoami) != "root" ] && echo "[ERROR] You must run this script with root priviliges." && exit 1
 SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
 KEYMAP=$1
-[ -z $KEYMAP ] && echo "[ERROR] You must specify a keymap!" && exit 1
+[ -z $KEYMAP ] && echo "[ERROR] No keymap specified - will default to US." && exit 1
 
 mkdir -P /etc/X11/xorg.conf.d
 localectl set-keymap $KEYMAP
@@ -10,7 +10,7 @@ XKEYMAP=$(localectl | grep -sm 1 "X11 Layout" | cut -c19-30)
 $SCRIPT_DIR/setvar set /etc/vconsole.conf KEYMAP $KEYMAP
 
 # Create X11 keyboard config
-echo "# This file was generated by Vapour OS. Any changes to this file will be lost after the next Vapour OS update or keymap configuration." > /etc/X11/xorg.conf.d/00-keyboard.conf
+echo "# This file was generated by Vapour OS. Any changes to this file will be lost after the next keymap configuration." > /etc/X11/xorg.conf.d/00-keyboard.conf
 echo "Section \"InputClass\"" >> /etc/X11/xorg.conf.d/00-keyboard.conf
 echo "    Identifier \"system-keyboard\"" >> /etc/X11/xorg.conf.d/00-keyboard.conf
 echo "    MatchIsKeyboard \"on\"" >> /etc/X11/xorg.conf.d/00-keyboard.conf
diff --git a/vapour-os/files/opt/vapour-os/locale b/vapour-os/files/opt/vapour-os/locale
--- a/vapour-os/files/opt/vapour-os/locale
+++ b/vapour-os/files/opt/vapour-os/locale
@@ -2,7 +2,7 @@
 [ $(whoami) != "root" ] && echo "[ERROR] You must run this script with root priviliges." && exit 1
 SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
 LOCALE=$1
-[ -z $LOCALE ] && echo "[ERROR] You must specify a locale!" && exit 1
+[ -z $LOCALE ] && echo "[ERROR] No locale specified - will default to en_US" && exit 1
 localectl set-locale $LOCALE
 echo "$LOCALE.UTF-8 UTF-8" > /etc/locale.gen
 echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen
