Submit to Crow Horse

diff --git a/vapour-os/files/opt/vapour-os/initramfs b/vapour-os/files/opt/vapour-os/initramfs
--- a/vapour-os/files/opt/vapour-os/initramfs
+++ b/vapour-os/files/opt/vapour-os/initramfs
@@ -1,17 +1,38 @@
 #!/bin/sh
+[ $(whoami) != "root" ] && echo "[ERROR] You must run this script with root priviliges." && exit 1
+if [ ! -z $1 -a $1 != "--novc" ]; then
+	echo "[ERROR] Unknown argument $1. Supported arguments are:"
+	"--novc  Do not add sd-vconsole hook. This can help if UEFI-CSM cannot be disabled, and the bootloader resolution is initially low and causes console text to appear huge before KMS."
+	exit 1
+fi
 SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
-. $SCRIPT_DIR/gpuinfo
+. $SCRIPT_DIR/pcihwinfo
+
+if [ ! -z $1 -a $1 == "--novc" ]; then HOOKS="autodetect base systemd"; else HOOKS="autodetect base systemd sd-vconsole"; fi
+HOOKS="$HOOKS modconf"
+if [ -f /usr/bin/plymouth ]; then HOOKS="$HOOKS sd-plymouth"; fi
+HOOKS="$HOOKS block filesystems keyboard fsck"
+
 echo "# This file was automatically generated by voscfg. Any changes to this file may be lost next time voscfg is run." > /etc/mkinitcpio.conf
-if [ ! -z $GPU0 ] && [ $GPU0 == "intel" ]; then echo "MODULES=(i915)" >> /etc/mkinitcpio.conf
-elif [ ! -z $GPU0 ] && [ $GPU0 == "amd" ]; then echo "MODULES=(amdgpu)" >> /etc/mkinitcpio.conf
-elif [ ! -z $GPU0 ] && [ $GPU0 == "nvidia" ]; then echo "MODULES=(nvidia efifb)" >> /etc/mkinitcpio.conf
+
+## Detect correct GPU modules for early KMS
+if [ ! -z $GPU0 ]; then
+	if [ $GPU0 == "intel" ] || [ $GPU0 == "intel-legacy" ]; then echo "MODULES=(i915)" >> /etc/mkinitcpio.conf
+	elif [ $GPU0 == "amd" ]; then echo "MODULES=(amdgpu)" >> /etc/mkinitcpio.conf
+	elif [ $GPU0 == "nvidia" ]; then echo "MODULES=(efifb nvidia nvidia_modeset nvidia_uvm nvidia_drm)" >> /etc/mkinitcpio.conf
+	elif [ $GPU0 == "std" ]; then echo "MODULES=(bochs bochs-drm)" >> /etc/mkinitcpio.conf
+	elif [ $GPU0 == "qxl" ]; then echo "MODULES=(qxl)" >> /etc/mkinitcpio.conf
+	elif [ $GPU0 == "virtio" ]; then echo "MODULES=(virtio-gpu)" >> /etc/mkinitcpio.conf
+	## The following GPUs are obsolete, however I decided to add partial support for them anyways because why not.
+	## I haven't tested these, and will not spend much or any time maintaining support for them.
+	elif [ $GPU0 == "vmware" ]; then echo "MODULES=(vmwgfx)" >> /etc/mkinitcpio.conf
+	elif [ $GPU0 == "cirrus" ]; then echo "MODULES=(cirrus)" >> /etc/mkinitcpio.conf
+	else echo "MODULES=()" >> /etc/mkinitcpio.conf; fi
 else echo "MODULES=()" >> /etc/mkinitcpio.conf; fi
+
 echo "BINARIES=()" >> /etc/mkinitcpio.conf
 echo "FILES=()" >> /etc/mkinitcpio.conf
-if [ -f /usr/bin/plymouth ]; then
-	echo "HOOKS=(autodetect base systemd sd-vconsole modconf sd-plymouth block filesystems keyboard fsck)" >> /etc/mkinitcpio.conf
-else
-	echo "HOOKS=(autodetect base systemd sd-vconsole modconf block filesystems keyboard fsck)" >> /etc/mkinitcpio.conf
+echo "HOOKS=($HOOKS)" >> /etc/mkinitcpio.conf
 fi
 echo "COMPRESSION=\"zstd\"" >> /etc/mkinitcpio.conf
 rm /boot/initramfs-*.img &> /dev/null
