k

diff --git a/pkgbuild/voscfg/files/usr/lib/voscfg/statichostname b/pkgbuild/voscfg/files/usr/lib/voscfg/statichostname
--- a/pkgbuild/voscfg/files/usr/lib/voscfg/statichostname
+++ b/pkgbuild/voscfg/files/usr/lib/voscfg/statichostname
@@ -14,13 +14,13 @@ if [ ! -z "$INPUT" ]; then
 	if ! [[ "$INPUT" =~ ^[0-9A-Za-z-]+$ ]]; then echo "[ERROR] Hostname contains illegal characters. Not changing hostname."; exit 1 # Check for illegal characters
 	elif (($(expr length "$INPUT") > 64)); then echo "[ERROR] Hostname is longer than 64 characters. Not changing hostname."; exit 1 # Check if hostname is too long
 	elif [ ${INPUT:0:1} == "-" ]; then echo "[ERROR] Hostname must not begin with a hyphen (-). Not changing hostname."; exit 1 # Check if hostname starts with hyphen
-	elif [ ${INPUT:0:1} == "_" ]; then echo "[ERROR] Hostname must not begin with a hyphen (-). Not changing hostname."; exit 1 # Check if hostname starts with underscore
+	elif [ ${INPUT:0:1} == "_" ]; then echo "[ERROR] Hostname must not begin with an underscore (_). Not changing hostname."; exit 1 # Check if hostname starts with underscore
 	fi
 
 	## Set the hostname
 	touch /etc/hostname /etc/hosts
 	unset OLD_HOSTNAME; OLD_HOSTNAME="$(cat /etc/hostname)"
-	hostnamectl --static hostname "$INPUT" || exit 1
+	hostnamectl --static hostname "$INPUT" || echo "$INPUT" > /etc/hostname
 
 	## Set hostname in /etc/hosts
 	EMPTY=1; while read -r LINE; do # Check if /etc/hosts is empty (no non-comment lines)
