Lots of fixes and improvements.

diff --git a/vapour-os/files/usr/lib/vapour-os/limine-install b/vapour-os/files/usr/lib/vapour-os/limine-install
--- a/vapour-os/files/usr/lib/vapour-os/limine-install
+++ b/vapour-os/files/usr/lib/vapour-os/limine-install
@@ -1,7 +1,16 @@
 #!/bin/bash
 DISTRO_ID="vapour-os"
 [ $(whoami) != "root" ] && echo "[ERROR] You must run this script with root priviliges." && exit 1
-. /usr/lib/$DISTRO_ID/diskinfo
+ROOT_UUID="$(cat /etc/fstab | grep " / " | cut -d ' ' -f 1)"
+if [ -z "$ROOT_UUID" ]; then
+	echo "[ERROR] You must set UUID=<root partition UUID> in /etc/fstab"
+	exit 1
+else ROOT_UUID=${ROOT_UUID#?????}; fi
+if [ ! -b "/dev/disk/by-uuid/$ROOT_UUID" ]; then
+	echo "[ERROR] /dev/disk/by-uuid/$ROOT_UUID does not exist! Please update the root UUID in /etc/fstab"
+	exit 1
+fi
+
 EFI_BITS="$(cat /sys/firmware/efi/fw_platform_size 2> /dev/null)"
 Upgrade() {
 	mkdir -p /boot/limine /boot/EFI/limine &> /dev/null
@@ -35,7 +44,7 @@ case "$1" in
 		KERNEL="${KERNEL_FILE:8}"
 		sed -i "s/^.*\${KERNEL}=.*$/\${KERNEL}=$KERNEL/" /boot/limine/limine.cfg
 		# Set ROOT_UUID
-		sed -i "s/^.*\${ROOT_UUID}=.*$/\${ROOT_UUID}=$ROOT_UUID/" /boot/limine/limine.cfg
+		sed -i "s/^.*\${ROOT_PARAMS}=.*$/\${ROOT_PARAMS}=rw root=UUID=$ROOT_UUID/" /boot/limine/limine.cfg
 		if [ -z "$EFI_BITS" ]; then # Create EFI boot entry (or don't)
 			echo "[WARNING] System was booted in BIOS mode. No UEFI boot entries were created."
 		elif [ "$EFI_BITS" == 32 ]; then efibootmgr -c -d $ROOT_DEV -p $BOOT_PART -L "Limine" -l '\EFI\Limine\BOOTIA32.EFI'
