gukjh

diff --git a/vapour-os-liveusb-installer/files/usr/bin/install-vapour-os b/vapour-os-liveusb-installer/files/usr/bin/install-vapour-os
--- a/vapour-os-liveusb-installer/files/usr/bin/install-vapour-os
+++ b/vapour-os-liveusb-installer/files/usr/bin/install-vapour-os
@@ -1,8 +1,12 @@
 #!/bin/bash
-[ "$(whoami)" != "root" ] && echo "[ERROR] You must run this installer as root" && exit 1
 DISTRO_ID="vapour-os"
 DISTRO_NAME="Vapour OS"
-[ ! -z "$DEBUG" ] && DEBUG=0; [ "$DEBUG" == 1 ] && echo "Debug mode enabled"
+ARCH="$(uname -m)"
+ARCH_VERSION="$(/lib/ld-linux-x86-64.so.2 --help | grep -m 1 "supported, searched" | cut -d '(' -f 1 | xargs)"
+CPU_MODEL="$(lscpu | grep -m 1 -i "Vendor ID:" | cut -d ':' -f 2 | xargs)"
+
+[ "$(whoami)" != "root" ] && echo "[ERROR] You must run this installer as root" && exit 1
+([ -z "$DEBUG" ] && [ "$DEBUG" != 1 ]) && DEBUG=0 || echo "Debug mode enabled"
 [ "$DEBUG" == 1 ] && BACKTITLE="$DISTRO_NAME installer (debug mode)" || BACKTITLE="$DISTRO_NAME installer"
 SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
 PAGE=0 # 0: Main menu, 1: Select preset, 2: Select root partition, 3: Select boot partition
@@ -348,8 +352,7 @@ while true; do
 			echo "Installation of $DISTRO_NAME has now begun. Grab a cup of tea, because this will take a while."
 			echo "DO NOT turn off your device or disconnect it from the internet."
 			echo; sleep 2
-			if [ "$DEBUG" == 1 ]; then (DEBUG=1 "/usr/lib/$DISTRO_ID/$DISTRO_ID-liveusb-installer" || exit 1)
-			else ("/usr/lib/$DISTRO_ID/$DISTRO_ID-liveusb-installer" || exit 1); fi
+			ARCH_VERSION="$ARCH_VERSION" CPU_MODEL="$CPU_MODEL" DEBUG="$DEBUG" "/usr/lib/$DISTRO_ID/$DISTRO_ID-liveusb-installer"
 			sync
 			echo; echo "Installation complete! You may reboot your computer."; exit 0;;
 	esac
