Fixed installers

diff --git a/vapour-os-liveusb-installer/files/usr/bin/vapour-os-installer-gui b/vapour-os-liveusb-installer/files/usr/bin/vapour-os-installer-gui
--- a/vapour-os-liveusb-installer/files/usr/bin/vapour-os-installer-gui
+++ b/vapour-os-liveusb-installer/files/usr/bin/vapour-os-installer-gui
@@ -1,4 +1,5 @@
 #!/bin/bash
+[ "$(whoami)" != "root" ] && echo "[ERROR] You must run this installer as root" && exit 1
 DISTRO_ID="vapour-os"
 DISTRO_NAME="Vapour OS"
 BACKTITLE="$DISTRO_NAME installer"
@@ -117,16 +118,179 @@ PartitionChooser() {
 		fi
 	fi
 }
+SelectVersion() {
+	VERSION_TO_INSTALL=$(dialog --stdout --backtitle "$BACKTITLE" --cancel-label "Back" --title "Version selection" --menu "Please select a version to install:" 0 0 0 \
+	"vapour-os-kde" "KDE Plasma (best for Windows users)" \
+	"vapour-os-xfce" "XFCE (best for older devices)" \
+	"vapour-os-gnome" "GNOME Shell (best for touch devices)" \
+	"vapour-os-desktop-libs" "Command line only (PCs/laptops)" \
+	"vapour-os" "Core system only (servers and embedded devices)")
+	[ -z "$VERSION_TO_INSTALL" ] && ((PAGE--)) || ((PAGE++))
+}
+SelectKernel() {
+	KERNELS="$(dialog --stdout --backtitle "$BACKTITLE" --cancel-label "Back" --title "Recommended software" --checklist "Select one or more Linux kernels to install:" 0 0 0 \
+	"linux-tt" "TT scheduler Linux kernel by CachyOS with other patches and improvements (recommended). May not boot on some BIOSes." "ON" \
+	"OFFICIALLY SUPPORTED" "" "OFF" \
+	"  linux" "Vanilla Linux kernel - use if linux-tt does not boot on your BIOS." "OFF" \
+	"  linux-hardened" "Security-Hardened Linux kernel and modules" "OFF" \
+	"  linux-lts" "Linux LTS kernel and modules" "OFF" \
+	"  linux-rt" "Linux realtime kernel and modules" "OFF" \
+	"  linux-rt-lts" "Linux realtime LTS kernel and modules" "OFF" \
+	"  linux-zen" "Linux ZEN kernel and modules" "OFF" \
+	"HARDWARE OPTIMISED" "" "OFF" \
+	"  linux-amd" "Linux kernel aimed at ZNVER4/MZEN4 AMD Ryzen CPU based hardware" "OFF" \
+	"  linux-amd-znver2" "Linux kernel aimed at znver2 AMD Ryzen CPU based hardware" "OFF" \
+	"  linux-amd-znver3" "Linux kernel aimed at znver3 AMD Ryzen CPU based hardware" "OFF" \
+	"  linux-hdr-git" "Linux kernel and modules with AMDGPU HDR support" "OFF" \
+	"  linux-nitrous" "Linux kernel and modules optimized for Skylake and newer, compiled using clang" "OFF" \
+	"LINUX-TKG" "" "OFF" \
+	"  linux-lts-tkg-bmq" "Linux-tkg BMQ scheduler LTS kernel and modules" "OFF" \
+	"  linux-lts-tkg-pds" "Linux-tkg PDS scheduler LTS kernel and modules" "OFF" \
+	"  linux-lts-tkg-tt" "Linux-tkg TT scheduler LTS kernel and modules" "OFF" \
+	"  linux-tkg" "Linux-tkg kernel and modules" "OFF" \
+	"  linux-tkg-bmq-generic_v3" "Linux-tkg BMQ scheduler kernel and modules" "OFF" \
+	"  linux-tkg-cfs" "Linux-tkg CFS scheduler kernel and modules" "OFF" \
+	"  linux-tkg-cfs-generic_v3" "Linux-tkg CFS scheduler kernel and modules" "OFF" \
+	"  linux-tkg-cfs-lto_v3" "Linux-tkg CFS scheduler kernel and modules" "OFF" \
+	"  linux-tkg-pds" "Linux-tkg PDS scheduler kernel and modules" "OFF" \
+	"  linux-tkg-pds-generic_v3" "Linux-tkg PDS scheduler kernel and modules" "OFF" \
+	"  linux-tkg-tt" "Linux-tkg TT scheduler kernel and modules" "OFF" \
+	"  linux-tkg-tt-generic_v3" "Linux-tkg TT scheduler kernel and modules" "OFF" \
+	"OTHER" "" "OFF" \
+	"  linux-cachyos-bore" "Linux BORE scheduler kernel and modules by CachyOS with other patches and improvements (recommended)" "OFF" \
+	"  linux-clear" "Intel's Clear Linux kernel and modules" "OFF" \
+	"  linux-drm-next-git" "Linux kernel and modules with bleeding-edge GPU drivers" "OFF" \
+	"  linux-drm-tip-git" "Linux kernel and modules with bleeding-edge GPU drivers" "OFF" \
+	"  linux-git" "Linus Torvalds' Mainline Linux kernel and modules" "OFF" \
+	"  linux-lqx" "Linux Liquorix kernel and modules" "OFF" \
+	"  linux-mainline" "Linux Mainline kernel and modules" "OFF" \
+	"  linux-next-git" "Linux NEXT kernel and modules" "OFF" \
+	"  linux-xanmod" "Linux kernel and modules with Xanmod patches" "OFF" \
+	"  linux-xanmod-lts" "Linux LTS kernel and modules with Xanmod patches" "OFF" \
+	"  linux-xanmod-rt" "Linux realtime kernel and modules with Xanmod patches" "OFF" \
+	)"
+	if [ ! -z "$KERNELS" ]; then # Remove category names from selection
+		KERNELS="${KERNELS/OFFICIALLY SUPPORTED/}"
+		KERNELS="${KERNELS/HARDWARE OPTIMISED/}"
+		KERNELS="${KERNELS/LINUX-TKG/}"
+		KERNELS="${KERNELS/OTHER/}"
+		KERNELS="$(echo "$KERNELS" | sed 's/\"//g')"
+	fi
+	[ -z "$KERNELS" ] && ((PAGE--)) || ((PAGE++))
+}
+SelectExtraSoftware() {
+	EXTRA_SOFTWARE="$(dialog --stdout --backtitle "BACKTITLE" --cancel-label "Skip" --title "Recommended software" --checklist "Would you like to install additional software?
+	See also https://wiki.archlinux.org/title/Category:Lists_of_software" 0 0 0 \
+	"GAMING" "" "OFF" \
+	"  vapour-os-gaming" "Linux/Windows game compatibility (64bit+32bit)" "OFF" \
+	"  dolphin-emu" "Nintendo Gamecube/Wii/Triforce emulator. NO GAMES OR COPYRIGHTED FILES INCLUDED - SOURCE THESE YOURSELF" "OFF" \
+	"  gzdoom" "Play DOOM engine games on modern PCs. NO GAMES OR COPYRIGHTED FILES INCLUDED - SOURCE THESE YOURSELF" "OFF" \
+	"  melonds-git" "Nintendo DS(i) emulator. NO GAMES OR COPYRIGHTED FILES INCLUDED - SOURCE THESE YOURSELF" "OFF" \
+	"  prismlauncher-qt5" "Open-source Minecraft Launcher and mod manager. YOU MUST PURCHASE MINECRAFT TO PLAY" "OFF" \
+	"  steam-native-runtime" "PC game storefront and launcher by Valve" "OFF" \
+	"INTERNET" "(for web browsers, scroll down further)" "OFF" \
+	"  discord" "Voice and video chat software" "OFF" \
+	"  qbittorrent" "Advanced BitTorrent client based on Qt" "OFF" \
+	"MULTIMEDIA" "" "OFF" \
+	"  gimp" "GNU Image Manipulation Program" "OFF" \
+	"  kolourpaint" "Paint program by KDE" "OFF" \
+	"  obs-studio" "Free open-source recording/streaming software" "OFF" \
+	"  vlc" "Multi-format media player/streamer and CD/VCD/DVD/BD player" "OFF" \
+	"OFFICE, TEXT" "" "OFF" \
+	"  nano" "Text editor for terminal" "OFF" \
+	"  onlyoffice-bin" "Office suite combining text, spreadsheet and presentation editors" "OFF" \
+	"SYSTEM" "" "OFF" \
+	"  gparted" "Graphical partition manager" "OFF" \
+	"WEB BROWSERS" "" "OFF" \
+	"  brave-bin" "Web browser that blocks ads and trackers by default" "OFF" \
+	"  chromium" "Open-source browser from which Google Chrome is based." "OFF" \
+	"    chromium-widevine" "Chromium plugin for viewing premium video content" "OFF" \
+	"    ublock-origin" "Chromium extension for blocking ads, trackers, miners, popups, malware sites and more. Fast, potent and lean." "OFF" \
+	"  firefox-i18n-en-gb" "Firefox browser (with British English language pack)" "OFF" \
+	"  firefox-i18n-en-us" "Firefox browser (with American English language pack)" "OFF" \
+	"  firefox-i18n-en-ca" "Firefox browser (with Canadian English language pack)" "OFF" \
+	"    firefox-ublock-origin" "Firefox extension for blocking ads, trackers, miners, popups, malware sites and more. Fast, potent and lean." "OFF" \
+	"  icecat" "GNU version of the Firefox browser." "OFF" \
+	"  librewolf" "Community-maintained fork of Firefox focused on privacy, security and freedom." "OFF" \
+	"  midori" "Lightweight web browser" "OFF" \
+	"  opera" "Fast and secure web browser" "OFF" \
+	"  vivaldi" "An advanced browser made with the power user in mind" "OFF" \
+	"CASUAL GAMES" "" "OFF" \
+	"  gnome-2048" "Slide numbered tiles on a grid to combine them to create a tile with the number 2048" "OFF" \
+	"  gnome-chess" "Computer version of Chess" "OFF" \
+	"  gnome-mahjongg" "Disassemble a pile of tiles by removing matching pairs" "OFF" \
+	"  gnome-mines" "Minesweeper clone" "OFF" \
+	"  gnome-nibbles" "Snake-like game, playable with up to 6 players" "OFF" \
+	"  gnome-sudoku" "Test your logic skills in this number grid puzzle" "OFF" \
+	"  gnome-taquin" "Sliding picture puzzle" "OFF" \
+	"  iagno" "Computer version of Reversi" "OFF" \
+	"  kfourinline" "Computer version of Connect 4" "OFF" \
+	"  kigo" "Computer version of Go" "OFF" \
+	"  khangman" "Hangman game" "OFF" \
+	"  knavalbattle" "Computer version of Battleships" "OFF" \
+	"  ksirk" "Computer version of Risk. Supports up to 6 human/AI players and network multiplayer" "OFF" \
+	"  kubrick" "Rubik's cube game" "OFF" \
+	"  lbreakout2" "Breakout inspired game with nice effects, graphics and sounds" "OFF" \
+	"  palapeli" "Single-player jigsaw puzzle game" "OFF" \
+	"  picmi" "Nonogram logic game similar to Picross" "OFF" \
+	"  puzzles " "Simon Tatham's Portable Puzzle Collection" "OFF" \
+	"  pysolfc" "Collection of over 1000 solitaire games" "OFF" \
+	"  quadrapassel" "Tetris clone" "OFF" \
+	"FREE GAMES" "" "OFF" \
+	"  0ad" "Historically-based real-time 3D strategy game" "OFF" \
+	"  cuyo" "Tetris-style puzzle game for up to two players with a twist" "OFF" \
+	"  dwarffortress" "Single-player fantasy game in which you build a dwarven outpost or play an adventurer in a randomly generated world" "OFF" \
+	"  glhack" "Port of Nethack, a single player dungeon exploration game in 2D" "OFF" \
+	"  hedgewars" "Worms clone. Take turns to blast your opponents into oblivion with comedic results!" "OFF" \
+	"  mari0" "Original Super Mario Bros with Portal gun mechanics" "OFF" \
+	"  shattered-pixel-dungeon" "Roguelike dungeon crawler with randomized levels and enemies, and hundreds of items" "OFF" \
+	"  supertux" "Super Mario style 2D platformer starring Tux" "OFF" \
+	"  supertuxkart" "Kart racing game featuring Tux and his friends" "OFF" \
+	"  wesnoth" "Free, turn-based tactical strategy game with a high fantasy theme, featuring both single-player, and online/hotseat multiplayer combat" "OFF" \
+	"EDUCATIONAL" "" "OFF" \
+	"  artikulate" "Improve your pronunciation by listening to native speakers" "OFF" \
+	"  blinken" "Memory enhancement game" "OFF" \
+	"  gcompris-qt" "Educational software suite comprising of numerous activities for children aged 2 to 10" "OFF" \
+	"  kalzium" "Periodic table of elements" "OFF" \
+	"  kanagram" "Letter order game" "OFF" \
+	"  kbruch" "Practice fractions and percentages" "OFF" \
+	"  kgeography" "Geography trainer" "OFF" \
+	"  klettres" "Learn the alphabet" "OFF" \
+	"  ktouch" "Touch typing tutor" "OFF" \
+	"  kturtle" "Turtlescript edcational programming environment" "OFF" \
+	"  marble" "Desktop globe with maps for Earth, the Moon and other planets" "OFF" \
+	"  minuet" "Music Education software by KDE" "OFF" \
+	"  scratch" "Create and share your own interactive stories, games, music and art" "OFF"
+	)"
+	if [ ! -z "$EXTRA_SOFTWARE" ]; then # Remove category names from selection
+		EXTRA_SOFTWARE="${EXTRA_SOFTWARE/GAMING/}"
+		EXTRA_SOFTWARE="${EXTRA_SOFTWARE/INTERNET/}"
+		EXTRA_SOFTWARE="${EXTRA_SOFTWARE/MULTIMEDIA/}"
+		EXTRA_SOFTWARE="${EXTRA_SOFTWARE/OFFICE, TEXT/}"
+		EXTRA_SOFTWARE="${EXTRA_SOFTWARE/SYSTEM/}"
+		EXTRA_SOFTWARE="${EXTRA_SOFTWARE/WEB BROWSERS/}"
+		EXTRA_SOFTWARE="${EXTRA_SOFTWARE/CASUAL GAMES/}"
+		EXTRA_SOFTWARE="${EXTRA_SOFTWARE/FREE GAMES/}"
+		EXTRA_SOFTWARE="${EXTRA_SOFTWARE/EDUCATIONAL/}"
+		EXTRA_SOFTWARE="$(echo "$EXTRA_SOFTWARE" | sed 's/\"//g')"
+	fi
+	if [ ! -z "$EXTRA_SOFTWARE" ]; then
+		[[ "$EXTRA_SOFTWARE" == *"chromium"* ]] && $EXTRA_SOFTWARE="$EXTRA_SOFTWARE chromium-widevine"
+		[[ "$EXTRA_SOFTWARE" == *"gparted"* ]] && $EXTRA_SOFTWARE="$EXTRA_SOFTWARE gpart mtools ntfs-3g"
+		[[ "$EXTRA_SOFTWARE" == *"vivaldi"* ]] && $EXTRA_SOFTWARE="$EXTRA_SOFTWARE vivaldi-ffmpeg-codecs"
+	fi
+	((PAGE++))
+}
 
 dialog --backtitle "$BACKTITLE" --title "Welcome" --msgbox "Thank you for choosing $DISTRO_NAME!
-We will never collect data or spy on you in any way.
-We will never restrict what you can do on your device.
-If you want to see how everything works, visit github.com/dankcuddlybear/vapourepo
+$DISTRO_NAME is open source - github.com/dankcuddlybear/vapourepo (some proprietary drivers are included)
+If you have issues with the installer, please file a bug report on the Github link above.
+If you have any other issues, please consult the excellent Arch Wiki (wiki.archlinux.org) or use a search engine before filing a bug report.
 Press ENTER to continue (or CTRL+C to quit at any time)." 0 0
 while true; do
 	case $PAGE in
 		0) # Main menu - choose normal or automated install
-			INSTALL_MODE=$(dialog --stdout --backtitle "$BACKTITLE" --cancel-label "Abort" --title "Main menu" --menu "What would you like to do?" 0 0 0 "1" "Install $DISTRO_NAME" "2" "Load preset for automated install (not yet available)")
+			INSTALL_MODE=$(dialog --stdout --backtitle "$BACKTITLE" --cancel-label "Exit" --title "Main menu" --menu "What would you like to do?" 0 0 0 "1" "Install $DISTRO_NAME" "2" "Load preset for automated install (not yet available)")
 			if [ -z $INSTALL_MODE ]; then clear; echo "Aborted installation."; exit # Abort installation if abort is selected
 			elif [ $INSTALL_MODE == 1 ]; then PAGE=2
 			elif [ $INSTALL_MODE == 2 ]; then PAGE=1
@@ -139,16 +303,19 @@ while true; do
 				PAGE=0
 			fi
 			;;
-		## Choose partitions
+		# Choose partitions
 		2) PartitionChooser;; 3) PartitionChooser;; 4) PartitionChooser;; 5) PartitionChooser;; 6) PartitionChooser;; 7) PartitionChooser;;
-		8) # Connect to the internet
+		8) SelectKernel;; 9) SelectVersion;; 10) SelectExtraSoftware;; # Choose extra software
+		11) # Connect to the internet
 			ping -c 1 archlinux.org &> /dev/null && INTERNET_CONNECTED=1 || INTERNET_CONNECTED=0
 			if [ $INTERNET_CONNECTED == 0 ]; then
-				dialog --backtitle "$BACKTITLE" --title "No internet connection" --yesno "It looks like you aren't connected to the internet. An internet connection is required to install $DISTRO_NAME. You may have recieved this warning in error, but you should verify your connection just to be safe.\n\nOpen NetworkManager menu?" 0 0 && nmtui
+				dialog --backtitle "$BACKTITLE" --title "No internet connection" --yesno \
+				"It looks like you aren't connected to the internet. An internet connection is required to install $DISTRO_NAME. Please verify that you are connected.
+				\nOpen NetworkManager menu?" 0 0 && nmtui
 			fi
 			((PAGE++))
 			;;
-		9) # Review settings before install
+		12) # Review settings before install
 			## Generate dialog text
 			FINALTEXT="$DISTRO_NAME is ready to be installed. Please review the following changes:\n[ROOT] $ROOT_DEV"
 			[ ! -z "$LABEL_ROOT" ] && FINALTEXT="$FINALTEXT \"$LABEL_ROOT\""; [ $FORMAT_ROOT == 1 ] && FINALTEXT="$FINALTEXT (format)"
@@ -166,9 +333,13 @@ while true; do
 				FINALTEXT="$FINALTEXT\n[SWAP] $SWAP_DEV"; [ ! -z "$LABEL_SWAP" ] && FINALTEXT="$FINALTEXT \"$LABEL_SWAP\""; FINALTEXT="$FINALTEXT (format)"
 			fi
 			FINALTEXT="$FINALTEXT\n\nApply changes and begin installation?"
- 			dialog --backtitle "$BACKTITLE" --title "Confirm changes" --yesno "$FINALTEXT" 0 0 && ((PAGE++)) || PAGE=7
+ 			dialog --backtitle "$BACKTITLE" --title "Confirm changes" --yesno "$FINALTEXT" 0 0 && ((PAGE++)) || PAGE=8
  			;;
-		10) # Begin installation
+		13) # Begin installation
+			clear
+			echo "Installation of $DISTRO_NAME has now begun. Grab a cup of tea, because this will take a while."
+			echo "DO NOT turn off your device or disconnect it from the internet."
+			sleep 2
 			"/usr/lib/$DISTRO_ID/$DISTRO_ID-liveusb-installer" || exit 1
 			sync
 			echo "Installation complete! You may reboot your computer."; exit;;
diff --git a/vapour-os-liveusb-installer/files/usr/lib/vapour-os/chroot-setup b/vapour-os-liveusb-installer/files/usr/lib/vapour-os/chroot-setup
--- a/vapour-os-liveusb-installer/files/usr/lib/vapour-os/chroot-setup
+++ b/vapour-os-liveusb-installer/files/usr/lib/vapour-os/chroot-setup
@@ -3,8 +3,6 @@ DISTRO_ID="vapour-os"
 DISTRO_NAME="Vapour OS"
 [ $(whoami) != "root" ] && echo "[ERROR] You must run this script with root priviliges." && exit 1
 SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
-[ -f "/$DISTRO_ID-live" ] && export VAPOUR_OS_INSTALL_MODE="buildiso" || export VAPOUR_OS_INSTALL_MODE="liveusb"
-[ "$VAPOUR_OS_INSTALL_MODE" == "buildiso" ] && touch /tmp/buildiso && touch /etc/$DISTRO_ID/buildiso
 ARCH="$(uname -m)"
 if [ -f "/etc/$DISTRO_ID/PROGRESS" ]; then PROGRESS="$(cat /etc/$DISTRO_ID/PROGRESS)"; else
 	PROGRESS=0
@@ -16,21 +14,22 @@ Checkpoint() {
 	sync
 }
 
-PACKAGES="$DISTRO_ID"
-DEF_DEPS="base iptables-nft"
+# Define packages and dependencies
+PACKAGES="$DISTRO_ID limine"
+DEF_DEPS="base"
+
+## TODO: Detect multiple kernels
+# Detect kernel
 if [ -f /boot/vmlinu*-linux* ]; then
 	KERNEL_FILE="$(basename "$(ls /boot/vmlinu*-linux* | tr '\n' ' ' | awk '{print $1}')")"
 	KERNEL="${KERNEL_FILE:8}"
-else KERNEL_FILE="vmlinuz-linux-tt"; KERNEL="linux-tt"; fi
+else KERNEL_FILE="vmlinuz-linux"; KERNEL="linux"; fi
 PACKAGES="$PACKAGES $KERNEL $KERNEL-headers"
-if [ "$VAPOUR_OS_INSTALL_MODE" == "buildiso" ]; then
-	PACKAGES="$PACKAGES firefox gparted vlc onlyoffice-bin qbittorrent hdapsd nano htop vapour-os-amdgpu vapour-os-i915 vapour-os-liveusb-installer vapour-os-multimedia vapour-os-nvidia vapour-os-printing vapour-os-xfce"
-	DEF_DEPS="pipewire wireplumber pipewire-jack pipewire-pulse xdg-desktop-portal-gtk"
-fi
 
 if [ $PROGRESS == 0 ]; then
-	echo "" > /etc/mkinitcpio.conf # Block initramfs creation until after Vapour OS has been installed
-	## Configure pacman
+	# Block initramfs creation until after Vapour OS has been installed
+	echo "" > /etc/mkinitcpio.conf
+	# Configure pacman
 	echo "[options]" > /etc/pacman.conf
 	echo "HoldPkg = amd-ucode base glibc intel-ucode pacman $DISTRO_ID" >> /etc/pacman.conf
 	echo "Architecture = auto" >> /etc/pacman.conf
@@ -38,8 +37,8 @@ if [ $PROGRESS == 0 ]; then
 	echo "#IgnoreGroup = " >> /etc/pacman.conf
 	echo "#NoUpgrade = " >> /etc/pacman.conf
 	echo "Color" >> /etc/pacman.conf
-	[ "$VAPOUR_OS_INSTALL_MODE" == "buildiso" ] && echo "#CheckSpace" >> /etc/pacman.conf || echo "CheckSpace" >> /etc/pacman.conf
-	([ "$VAPOUR_OS_INSTALL_MODE" == "buildiso" ] || (($(nproc) <= 5))) && echo "ParallelDownloads = 5" >> /etc/pacman.conf || echo "ParallelDownloads = $(nproc)" >> /etc/pacman.conf
+	echo "CheckSpace" >> /etc/pacman.conf
+	echo "ParallelDownloads = $(nproc)" >> /etc/pacman.conf
 	echo "SigLevel = Required DatabaseOptional" >> /etc/pacman.conf
 	echo "LocalFileSigLevel = Optional" >> /etc/pacman.conf
 	echo "" >> /etc/pacman.conf
@@ -57,24 +56,26 @@ if [ $PROGRESS == 0 ]; then
 	Checkpoint 1
 fi
 
-if [ $PROGRESS == 1 ]; then
+if [ $PROGRESS == 1 ]; then # Download and locally sign Chaotic-AUR keys
 	pacman-key --recv-key FBA220DFC880C036 --keyserver keyserver.ubuntu.com || exit 1
 	pacman-key --lsign-key FBA220DFC880C036
 	Checkpoint 2
 fi; if [ $PROGRESS == 2 ]; then
+	# Install Chaotic-AUR keyring and mirrorlist
 	pacman --needed --noconfirm --asdeps -U 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-keyring.pkg.tar.zst' 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-mirrorlist.pkg.tar.zst' || exit 1
 	echo "" >> /etc/pacman.conf
+	# Add extra repositories to pacman.conf
 	echo "[chaotic-aur]" >> /etc/pacman.conf
 	echo "Include = /etc/pacman.d/chaotic-mirrorlist" >> /etc/pacman.conf
 	echo "" >> /etc/pacman.conf
 	echo "[vapourepo]" >> /etc/pacman.conf
-	echo "SigLevel = Optional DatabaseOptional" >> /etc/pacman.conf
 	echo "Include = /etc/pacman.d/vapour-os-mirrorlist.tmp" >> /etc/pacman.conf
+	## TODO: Verify that all keys are properly added to the system
 	Checkpoint 3
 fi
 
-if [ $PROGRESS == 3 ]; then
-	curl -o /etc/pacman.d/vapour-os-mirrorlist.tmp https://raw.githubusercontent.com/dankcuddlybear/vapourepo/main/vapour-os/files/etc/pacman.d/vapour-os-mirrorlist || exit 1
+if [ $PROGRESS == 3 ]; then # Download temporary Vapour OS mirrorlist
+	curl -o /etc/pacman.d/vapour-os-mirrorlist.tmp https://raw.githubusercontent.com/dankcuddlybear/vapourepo/main/vapour-os-mirrorlist/etc/pacman.d/vapour-os-mirrorlist || exit 1
 	Checkpoint 4
 fi
 
@@ -89,61 +90,51 @@ if [ $PROGRESS == 4 ]; then
 fi; if [ $PROGRESS == 5 ]; then
 	pacman --needed --noconfirm --asdeps -Su $DEF_DEPS || exit 1
 	pacman --needed --noconfirm -Su $PACKAGES || exit 1
-	pacman --asdeps -D $DEF_DEPS
 	Checkpoint 6
 fi
 
 if [ $PROGRESS == 6 ]; then
-	locale-gen
-	ln -sf /usr/share/zoneinfo/Europe/London /etc/localtime
-	/usr/bin/syscfg dictionary british-english
-	limine-install install
-	timedatectl set-ntp true
-	usermod -L root
-	fscrypt setup --force --quiet
-	rm /boot/initramfs-*.img &> /dev/null; mkinitcpio -P
-
-	## Reconfigure pacman
+	# Reconfigure pacman
 	sed -i "/^#CheckSpace/ cCheckSpace" /etc/pacman.conf
 	sed -i "s/Include = \/etc\/pacman.d\/vapour-os-mirrorlist.tmp/Include = \/etc\/pacman.d\/vapour-os-mirrorlist/g" /etc/pacman.conf
 	rm /etc/pacman.d/vapour-os-mirrorlist.tmp
 	pacman --noconfirm -Sc
-
-	## Configure sudo
-	echo "Defaults passwd_timeout=0" > /etc/sudoers
-	echo "Defaults insults" >> /etc/sudoers
-	echo "root ALL=(ALL:ALL) ALL" >> /etc/sudoers
-	echo "%wheel ALL=(ALL) ALL" >> /etc/sudoers
-	echo "@includedir /etc/sudoers.d" >> /etc/sudoers
-	chmod 660 /etc/sudoers
-
-	if [ "$VAPOUR_OS_INSTALL_MODE" == "buildiso" ]; then
-		useradd -m live
-		passwd -d live
-		groupadd -r autologin
-		gpasswd -a live wheel
-		gpasswd -a live autologin
-		echo "$DISTRO_ID-live" > /etc/hostname
-		echo "127.0.0.1 localhost" > /etc/hosts
-		echo "::1 localhost" >> /etc/hosts
-		echo "127.0.1.1 $DISTRO_ID-live" >> /etc/hosts
-		echo "PRETTY_HOSTNAME=\"Vapour OS $ARCH Live\"" > /etc/machine-info
-	else
-		# Configure users
-		NUM_USERS=0; while ((NUM_USERS < 1)); do
-			NUM_USERS="$(ls -I shared -I initsetup /home | wc -w)"
-			((NUM_USERS < 1)) && /usr/bin/syscfg users add
-		done
-		# Configure hostname
-		HOSTNAME=""; while [ -z "$HOSTNAME" ]; do
-			HOSTNAME="$(cat /etc/hostname)"
-			[ -z "$HOSTNAME" ] && /usr/bin/syscfg hostname
-		done
-		# FSCrypt
-		. /usr/lib/vapour-os/diskinfo
-		[ ! -z $HOME_DEV ] && fscrypt setup /home --force --quiet
-		[ ! -z $MEDIA_DEV ] && fscrypt setup /media --force --quiet
-	fi
+	
+	# FSCrypt
+	. /usr/lib/vapour-os/diskinfo
+	[ ! -z $HOME_DEV ] && fscrypt setup /home --force --quiet
+	[ ! -z $MEDIA_DEV ] && fscrypt setup /media --force --quiet
+	
+	# Install Limine bootloader
+	
+	# Add user
+	CONTINUE=0; while [ $CONTINUE == 0 ]; do
+		echo "[ATTENTION] Please enter an owner's username. This user will have administrator priviliges."
+		unset USER_NAME; read USER_NAME
+		if [ -z "$USER_NAME" ]; then echo "[ERROR] No username provided"
+		else
+			useradd -m "$USER_NAME" && CONTINUE=1 || CONTINUE=0
+		fi
+	done
+	passwd -d "$USER_NAME"; gpasswd -a "$USER_NAME" wheel
+	CONTINUE=0; while [ $CONTINUE == 0 ]; do
+		echo "[ATTENTION] Please enter a password for that owner's account."
+		passwd "$USER_NAME" && CONTINUE=1 || CONTINUE=0
+	done
+	
+	# Set hostname
+	CONTINUE=0; while [ $CONTINUE == 0 ]; do
+		echo "[ATTENTION] Please enter a hostname for this computer"
+		unset HOST_NAME; read HOST_NAME
+		if [ -z "$HOST_NAME" ]; then echo "[ERROR] No hostname provided"
+		else
+			echo "$HOST_NAME" > /etc/hostname
+			echo "127.0.0.1 localhost" > /etc/hosts
+			echo "::1 localhost" >> /etc/hosts
+			echo "127.0.1.1 $HOST_NAME" >> /etc/hosts
+			CONTINUE=1
+		fi
+	done
 	rm /etc/$DISTRO_ID/PROGRESS
 	sync
 fi
diff --git a/vapour-os-liveusb-installer/files/usr/lib/vapour-os/vapour-os-liveusb-installer b/vapour-os-liveusb-installer/files/usr/lib/vapour-os/vapour-os-liveusb-installer
--- a/vapour-os-liveusb-installer/files/usr/lib/vapour-os/vapour-os-liveusb-installer
+++ b/vapour-os-liveusb-installer/files/usr/lib/vapour-os/vapour-os-liveusb-installer
@@ -3,110 +3,135 @@ DISTRO_ID="vapour-os"
 DISTRO_NAME="Vapour OS"
 [ $(whoami) != "root" ] && echo "[ERROR] You must run this script with root priviliges." && exit 1
 SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
-[ -z "$VAPOUR_OS_INSTALL_MODE" ] && export VAPOUR_OS_INSTALL_MODE="liveusb"
-E2OPTIONS="ea_inode,encrypt,fast_commit,inline_data,large_dir,quota,uninit_bg"
+E2OPTIONS="ea_inode,encrypt,fast_commit,inline_data,large_dir,quota,uninit_bg,verity"
+ARCH="$(uname -m)"
 unset PARTITION_NOT_FOUND
 timedatectl set-ntp true
 sync
 
-## Check that each partition exists, and resolve links
-ValidatePartition() {
+## 1) Prepare and mount filesystems
+echo "Preparing file systems..."
+ValidatePartition() { # Checks that each partition exists, and resolves links
 	if [ ! -z "$1" ]; then
 		if [ -b "$1" ]; then echo "$(readlink -f "$1")"; else PARTITION_NOT_FOUND=1; fi
 	fi
 }
-
-if [ "$VAPOUR_OS_INSTALL_MODE" != "buildiso" ]; then
-	[ -z "$ROOT_DEV" ] && echo "[ERROR] No root partition specified. Please set variable ROOT_DEV to the root partition." && exit 1
-	[ -z "$BOOT_DEV" ] && echo "[ERROR] No EFI system partition specified. Please set variable BOOT_DEV to the ESP." && exit 1
-	ROOT_DEV="$(ValidatePartition "$ROOT_DEV")"; [ ! -z $PARTITION_NOT_FOUND ] && echo "[ERROR] Root partition $ROOT_DEV does not exist!" && exit 1
-	BOOT_DEV="$(ValidatePartition "$BOOT_DEV")"; [ ! -z $PARTITION_NOT_FOUND ] && echo "[ERROR] EFI system partition $BOOT_DEV does not exist!" && exit 1
-	HOME_DEV="$(ValidatePartition "$HOME_DEV")"; [ ! -z $PARTITION_NOT_FOUND ] && echo "[ERROR] Home partition $HOME_DEV does not exist!" && exit 1
-	MEDIA_DEV="$(ValidatePartition "$MEDIA_DEV")"; [ ! -z $PARTITION_NOT_FOUND ] && echo "[ERROR] Media partition $MEDIA_DEV does not exist!" && exit 1
-	PUBLIC_DEV="$(ValidatePartition "$PUBLIC_DEV")"; [ ! -z $PARTITION_NOT_FOUND ] && echo "[ERROR] Public partition $PUBLIC_DEV does not exist!" && exit 1
-	SWAP_DEV="$(ValidatePartition "$SWAP_DEV")"; [ ! -z $PARTITION_NOT_FOUND ] && echo "[ERROR] Swap partition $SWAP_DEV does not exist!" && exit 1
-
-	## Unmount any mounted filesystems
-	if [ ! -z "$SWAP_DEV" ] && [ ! -z "$(cat /proc/swaps | grep "$SWAP_DEV")" ]; then # Unmount mounted swap partition
-		swapoff "$SWAP_DEV" || (echo "[ERROR] Failed to unmount $FS"; exit 1)
-	fi
-	for FS in "$BOOT_DEV" "$HOME_DEV" "$MEDIA_DEV" "$PUBLIC_DEV" "$ROOT_DEV"; do
-		if [ ! -z "$FS" ] && [ ! -z "$(mount | grep "$FS")" ]; then # Unmount mounted filesystem
-			umount -f "$FS" || (echo "[ERROR] Failed to unmount $FS"; exit 1)
-		fi
-	done; unset FS
-
-	## Format any filesystems marked for formatting
-	[ ! -z $FORMAT_ROOT ] && [ $FORMAT_ROOT == 1 ] && mkfs.ext4 -FL "$LABEL_ROOT" -O $E2OPTIONS "$ROOT_DEV"
-	[ ! -z $FORMAT_BOOT ] && [ $FORMAT_BOOT == 1 ] && mkfs.fat -F 32 -n "$LABEL_BOOT" "$BOOT_DEV"
-	[ ! -z "$HOME_DEV" ] && [ ! -z $FORMAT_HOME ] && [ $FORMAT_HOME == 1 ] && mkfs.ext4 -FL "$LABEL_HOME" -O $E2OPTIONS "$HOME_DEV"
-	[ ! -z "$MEDIA_DEV" ] && [ ! -z $FORMAT_MEDIA ] && [ $FORMAT_MEDIA == 1 ] && mkfs.ext4 -FL "$LABEL_MEDIA" -O $E2OPTIONS "$MEDIA_DEV"
-	[ ! -z "$PUBLIC_DEV" ] && [ ! -z $FORMAT_PUBLIC ] && [ $FORMAT_PUBLIC == 1 ] && mkfs.ext4 -FL "$LABEL_PUBLIC" -O $E2OPTIONS "$PUBLIC_DEV"
-	[ ! -z "$SWAP_DEV" ] && mkswap -L "$LABEL_SWAP" "$SWAP_DEV"
-
-	## Tune filesystems and force fsck every mount
-	tune2fs -O $E2OPTIONS -c 1 "$ROOT_DEV"
-	[ ! -z "$HOME_DEV" ] && tune2fs -O $E2OPTIONS -c 1 "$HOME_DEV"
-	[ ! -z "$MEDIA_DEV" ] && tune2fs -O $E2OPTIONS -c 1 "$MEDIA_DEV"
-	[ ! -z "$PUBLIC_DEV" ] && tune2fs -O $E2OPTIONS -c 1 "$PUBLIC_DEV"
-
-	## Set boot flag on ESP
-	BOOT_DEV="$(readlink -f "$BOOT_DEV")"
-	if [ "${BOOT_DEV:5:2}" == "hd" ] || [ "${BOOT_DEV:5:2}" == "sd" ] || [ "${BOOT_DEV:5:2}" == "vd" ]; then
-		ESPDISK="${BOOT_DEV:0:8}"
-		ESPPART="${BOOT_DEV:8:3}"
-	elif [ "${BOOT_DEV:5:4}" == "nvme" ]; then
-		ESPDISK="${BOOT_DEV:0:12}"
-		ESPPART="${BOOT_DEV:13:3}"
-	elif [ "${BOOT_DEV:5:6}" == "mmcblk" ]; then
-		ESPDISK="${BOOT_DEV:0:12}"
-		ESPPART="${BOOT_DEV:13:3}"
-	else echo "[ERROR] Error detecting EFI system partition!"; exit 1; fi
-	parted "$ESPDISK" set "$ESPPART" boot on 1> /dev/null
-
-	## Mount and clear root filesystem
-	mount "$ROOT_DEV" /mnt
-	[ "$FORMAT_ROOT" != 1 ] && rm -rf /mnt/bin /mnt/dev /mnt/etc /mnt/lib /mnt/lib64 /mnt/mnt /mnt/opt /mnt/proc /mnt/root /mnt/run /mnt/sbin /mnt/sys /mnt/tmp /mnt/usr /mnt/var
+[ -z "$ROOT_DEV" ] && echo "[ERROR] No root partition specified. Please set variable ROOT_DEV to the root partition." && exit 1
+[ -z "$BOOT_DEV" ] && echo "[ERROR] No EFI system partition specified. Please set variable BOOT_DEV to the ESP." && exit 1
+ROOT_DEV="$(ValidatePartition "$ROOT_DEV")"; [ ! -z $PARTITION_NOT_FOUND ] && echo "[ERROR] Root partition $ROOT_DEV does not exist!" && exit 1
+BOOT_DEV="$(ValidatePartition "$BOOT_DEV")"; [ ! -z $PARTITION_NOT_FOUND ] && echo "[ERROR] EFI system partition $BOOT_DEV does not exist!" && exit 1
+HOME_DEV="$(ValidatePartition "$HOME_DEV")"; [ ! -z $PARTITION_NOT_FOUND ] && echo "[ERROR] Home partition $HOME_DEV does not exist!" && exit 1
+MEDIA_DEV="$(ValidatePartition "$MEDIA_DEV")"; [ ! -z $PARTITION_NOT_FOUND ] && echo "[ERROR] Media partition $MEDIA_DEV does not exist!" && exit 1
+PUBLIC_DEV="$(ValidatePartition "$PUBLIC_DEV")"; [ ! -z $PARTITION_NOT_FOUND ] && echo "[ERROR] Public partition $PUBLIC_DEV does not exist!" && exit 1
+SWAP_DEV="$(ValidatePartition "$SWAP_DEV")"; [ ! -z $PARTITION_NOT_FOUND ] && echo "[ERROR] Swap partition $SWAP_DEV does not exist!" && exit 1
+# Unmount any mounted filesystems
+if [ ! -z "$SWAP_DEV" ] && [ ! -z "$(cat /proc/swaps | grep "$SWAP_DEV")" ]; then # Unmount mounted swap partition
+	echo "$SWAP_DEV is still in use, unmounting..."
+	sync; swapoff "$SWAP_DEV" || (echo "[ERROR] Failed to unmount $SWAP_DEV"; exit 1)
 fi
-
-## Create mount points
+for FS in "$BOOT_DEV" "$HOME_DEV" "$MEDIA_DEV" "$PUBLIC_DEV" "$ROOT_DEV"; do
+if [ ! -z "$FS" ] && [ ! -z "$(mount | grep "$FS")" ]; then # Unmount mounted filesystem
+		echo "$FS is still in use, unmounting..."
+		sync; umount -f "$FS" || (echo "[ERROR] Failed to unmount $FS"; exit 1)
+	fi
+done; unset FS
+# Format and tune root and boot partition, if marked for formatting
+[ ! -z $FORMAT_ROOT ] && [ $FORMAT_ROOT == 1 ] && echo "Formatting root (/) partition" && mkfs.ext4 -FL "$LABEL_ROOT" -O $E2OPTIONS "$ROOT_DEV"
+echo "Tuning root (/) partition"; tune2fs -O $E2OPTIONS -c 1 "$ROOT_DEV"
+[ ! -z $FORMAT_BOOT ] && [ $FORMAT_BOOT == 1 ] && echo "Formatting /boot partition" && mkfs.fatF 32 -n "$LABEL_BOOT" "$BOOT_DEV"
+# Set boot flag on /boot partition
+echo "Making /boot partition bootable"
+BOOT_DEV="$(readlink -f "$BOOT_DEV")"
+if [ "${BOOT_DEV:5:2}" == "hd" ] || [ "${BOOT_DEV:5:2}" == "sd" ] || [ "${BOOT_DEV:5:2}" == "vd" ]; then
+	ESPDISK="${BOOT_DEV:0:8}"
+	ESPPART="${BOOT_DEV:8:3}"
+elif [ "${BOOT_DEV:5:4}" == "nvme" ]; then
+	ESPDISK="${BOOT_DEV:0:12}"
+	ESPPART="${BOOT_DEV:13:3}"
+elif [ "${BOOT_DEV:5:6}" == "mmcblk" ]; then
+	ESPDISK="${BOOT_DEV:0:12}"
+	ESPPART="${BOOT_DEV:13:3}"
+else echo "[ERROR] Error detecting /boot partition!"; exit 1; fi
+parted "$ESPDISK" set "$ESPPART" boot on 1> /dev/null
+# Format and tune other partitions, if marked for formatting
+if [ ! -z "$HOME_DEV" ]; then
+	[ ! -z $FORMAT_HOME ] && [ $FORMAT_HOME == 1 ] && echo "Formatting /home partition" && mkfs.ext4 -FL "$LABEL_HOME" -O $E2OPTIONS "$HOME_DEV"
+	echo "Tuning /home partition"; tune2fs -O $E2OPTIONS -c 1 "$HOME_DEV"
+fi
+if [ ! -z "$MEDIA_DEV" ]; then
+	[ ! -z $FORMAT_MEDIA ] && [ $FORMAT_MEDIA == 1 ] && echo "Formatting /media partition" && mkfs.ext4 -FL "$LABEL_MEDIA" -O $E2OPTIONS "$MEDIA_DEV"
+	echo "Tuning /media partition"; tune2fs -O $E2OPTIONS -c 1 "$MEDIA_DEV"
+fi
+if [ ! -z "$PUBLIC_DEV" ]; then
+	[ ! -z $FORMAT_PUBLIC ] && [ $FORMAT_PUBLIC == 1 ] && echo "Formatting /public partition" && mkfs.ext4 -FL "$LABEL_PUBLIC" -O $E2OPTIONS "$PUBLIC_DEV"
+	echo "Tuning /public partition"; tune2fs -O $E2OPTIONS -c 1 "$PUBLIC_DEV"
+[ ! -z "$SWAP_DEV" ] && echo "Formatting swap partition" && mkswap -L "$LABEL_SWAP" "$SWAP_DEV"
+# Mount and clear root filesystem
+echo "Mounting root (/) partition"; mount "$ROOT_DEV" /mnt
+if [ "$FORMAT_ROOT" != 1 ]; then
+	echo "Deleting old Linux files from root (/) partition"
+	rm -rf /mnt/bin /mnt/dev /mnt/etc /mnt/lib /mnt/lib64 /mnt/mnt /mnt/opt /mnt/proc /mnt/root /mnt/run /mnt/sbin /mnt/sys /mnt/tmp /mnt/usr /mnt/var
+fi
+# Create mount points
+echo "Creating mount points..."
 mkdir "/mnt/boot" &> /dev/null
 mkdir "/mnt/public" &> /dev/null; chmod 777 "/mnt/public"; chmod +t "/mnt/public"
-
-if [ "$VAPOUR_OS_INSTALL_MODE" != "buildiso" ]; then
-	## Create mount points
-	[ ! -z "$HOME_DEV" ] && mkdir /mnt/home &> /dev/null
-	[ ! -z "$MEDIA_DEV" ] && mkdir /mnt/media &> /dev/null && chmod 777 /mnt/media && chmod +t /mnt/media
-	## Mount and clear other filesystems
-	mount "$BOOT_DEV" /mnt/boot
-	[ $FORMAT_BOOT != 1 ] && rm -rf /mnt/boot/*.img /mnt/boot/vmlinu* /mnt/boot/EFI/systemd /mnt/boot/loader
-	[ ! -z "$HOME_DEV" ] && mount "$HOME_DEV" /mnt/home
-	[ ! -z "$MEDIA_DEV" ] && mount "$MEDIA_DEV" /mnt/media
-	[ ! -z "$PUBLIC_DEV" ] && mount "$PUBLIC_DEV" /mnt/public
+[ ! -z "$HOME_DEV" ] && mkdir /mnt/home &> /dev/null
+[ ! -z "$MEDIA_DEV" ] && mkdir /mnt/media &> /dev/null && chmod 777 /mnt/media && chmod +t /mnt/media
+# Mount and clear other filesystems
+mount "$BOOT_DEV" /mnt/boot; echo "Mounted /boot"
+if [ $FORMAT_BOOT != 1 ]; then
+	echo "Deleting old Linux files from /boot partition"
+	rm -rf /mnt/boot/*.img /mnt/boot/vmlinu* /mnt/boot/EFI/systemd /mnt/boot/limine /mnt/boot/loader
 fi
+[ ! -z "$HOME_DEV" ] && mount "$HOME_DEV" /mnt/home && echo "Mounted /home"
+[ ! -z "$MEDIA_DEV" ] && mount "$MEDIA_DEV" /mnt/media && echo "Mounted /media"
+[ ! -z "$PUBLIC_DEV" ] && mount "$PUBLIC_DEV" /mnt/public && echo "Mounted /public"
 sync
 
-## Auto-detect hardware
-PACKAGES="base iptables-nft"
+## 2) Auto-detect required packages
+PACKAGES="base"
+# Detect CPU microcode
 CPU_VENDOR_ID="$(lscpu | grep "Vendor ID:" | awk '{print $NF}')"
-if [ $VAPOUR_OS_INSTALL_MODE == "buildiso" ]; then PACKAGES="$PACKAGES amd-ucode intel-ucode"
-elif [ "$CPU_VENDOR_ID" == "AuthenticAMD" ]; then PACKAGES="$PACKAGES amd-ucode"
-elif [ "$CPU_VENDOR_ID" == "GenuineIntel" ]; then PACKAGES="$PACKAGES intel-ucode"; fi
+if [ "$CPU_VENDOR_ID" == "AuthenticAMD" ]; then PACKAGES="$PACKAGES amd-ucode"; echo "Found AMD $ARCH CPU"
+elif [ "$CPU_VENDOR_ID" == "GenuineIntel" ]; then PACKAGES="$PACKAGES intel-ucode"; echo "Found Intel $ARCH CPU"
+else echo "Found unknown $ARCH CPU"
+# Detect laptop hardware
 CHASSIS="$(dmidecode -s chassis-type)"
-if [ $VAPOUR_OS_INSTALL_MODE != "buildiso" ] && [ ! -z "$CHASSIS" ] && ([ "$CHASSIS" == "Portable" ] || [ "$CHASSIS" == "Laptop" ] || [ "$CHASSIS" == "Notebook" ] || \
-[ "$CHASSIS" == "Convertible" ] || [ "$CHASSIS" == "Detachable" ] || [ "$CHASSIS" == "Tablet" ] || [ "$CHASSIS" == "Hand Held" ]); then
-	JOYSTICKS="$(ls /dev/js*)"; if [ ! -z "$JOYSTICKS" ]; then PACKAGES="$PACKAGES hdapsd"; fi
+if [ ! -z "$CHASSIS" ] && ([ "$CHASSIS" == "Laptop" ] || [ "$CHASSIS" == "Notebook" ] || \
+[ "$CHASSIS" == "Convertible" ] || [ "$CHASSIS" == "Detachable" ] || [ "$CHASSIS" == "Tablet" ] || \
+[ "$CHASSIS" == "Hand Held" ] || [ "$CHASSIS" == "Portable" ]); then
+	echo "Device is portable (type $CHASSIS)"
+	if [ ! -z "$CHASSIS" ] && ([ "$CHASSIS" == "Laptop" ] || [ "$CHASSIS" == "Notebook" ] || \
+	[ "$CHASSIS" == "Convertible" ] || [ "$CHASSIS" == "Detachable" ] || [ "$CHASSIS" == "Tablet" ]); then
+		if [ -f /dev/freefall ]; then
+			echo "Found freefall sensor"
+			PACKAGES="$PACKAGES hdapsd"
+		fi
+	fi
+else echo "Device is type $CHASSIS"; fi
+# Install extra non-dependency packages depending on version to be installed
+if [ "$VERSION_TO_INSTALL" != "vapour-os" ]
+	# Install Pipewire first to avoid dependency conflicts
+	PACKAGES="$PACKAGES lib32-pipewire-jack pipewire-alsa pipewire-jack pipewire-pulse wireplumber"
+	# Install the right XDG desktop portal
+	case "$VERSION_TO_INSTALL" in
+		vapour-os-gnome) PACKAGES="$PACKAGES xdg-desktop-portal-gnome";;
+		vapour-os-kde) PACKAGES="$PACKAGES xdg-desktop-portal-kde";;
+		vapour-os-xfce) PACKAGES="$PACKAGES xdg-desktop-portal-gtk";;
+	esac
 fi
 
-## Bootstrap packages. If it fails for some reason, abort installation.
+## 3) Install packages
+echo "Bootstrapping a minimal system..."
 pacstrap /mnt $PACKAGES || exit 1
 sync
 
-## Finish install in chroot
+## 4) Finish install in chroot
 mkdir -p "/mnt/etc/$DISTRO_ID"
 cp $SCRIPT_DIR/chroot-setup "/mnt/etc/$DISTRO_ID/chroot-setup"
-[ "$VAPOUR_OS_INSTALL_MODE" == "buildiso" ] && touch "/mnt/$DISTRO_ID-live"
 sync
+echo "Installing in chroot..."
 arch-chroot /mnt "/etc/$DISTRO_ID/chroot-setup"
 rm "/mnt/etc/$DISTRO_ID/chroot-setup"
 sync
